// <auto-generated />
using Commerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "X 100pre is the debut studio album by Puerto Rican rapper Bad Bunny. It was released on December 24, 2018 on Christmas Eve, by Rimas Entertainment.",
                            ImagenUrl = "https://media.pitchfork.com/photos/5c2cdf59673bd655963c817c/1:1/w_320/X%20100PRE_Bad%20Bunny.jpg",
                            Price = 9.99m,
                            Title = "X100pre"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Microdosis, which has 15 songs and the same number of music videos, also includes a collaboration with Latin artist Elena Rose and Feid, Mora's representatives detailed in a press release.",
                            ImagenUrl = "https://i.scdn.co/image/ab67616d0000b273851222dc5c5681bd4c3119d3",
                            Price = 9.99m,
                            Title = "Microdosis"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sentimiento, Elegancia, & Maldad (S.E.M.) (English: Sentiment, Elegance, & Malice) is the first studio album by singer-songwriter Arcángel. It was released on November 19, 2013, by Pina Records. The first single from the album, Hace Mucho Tiempo, was released on June 21, 2013.",
                            ImagenUrl = "https://upload.wikimedia.org/wikipedia/en/d/d3/Sentimiento%2CEleganciaYMaldad.JPEG",
                            Price = 9.99m,
                            Title = "S.E.M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
